### PR TITLE
chore: update version to 0.3.0 dev

### PR DESCRIPTION
**Pull request by TimoGlastra**
Need to wait with releasing until #177 is merged

@andrewwhitehead  @berendsliedrecht @genaris all good to make a first 0.3.0 dev release?

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
Yes, sounds good to me.

**Comment by swcurran** [comment]
With #177 now merged, can someone take on the version updating and tagging?

**Comment by TimoGlastra** [comment]
It seems the windows tests are still failing @andrewwhitehead. Do you know what's going on here?

**Comment by TimoGlastra** [comment]
Oh it seems #183 maybe solves this.

**Review by berendsliedrecht — APPROVED** [review]

**Pull request merged**
