### PR TITLE
fix: fix transactions to rollback on failure

### PR DESCRIPTION
**Pull request by reflectivedevelopment**
When we have a transaction fail we should roll back the transaction.

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
I don't immediately see why this is necessary. If the DBSession is dropped without committing the transaction (which happens if the process short-circuits due to an error) then it should roll-back automatically.

**Comment by reflectivedevelopment** [comment]
I've been seeing issues with the transactions not being closed after failure, so I added this code to explicitly close them. It appears that the connections are returned to the pool with the transaction still being active.

**Comment by reflectivedevelopment** [comment]
I'm seeing errors like this.

`Traceback (most recent call last):
   File "/cloudagent/aries_cloudagent/wallet/askar.py\
 line 199, in create_local_did
     await self._session.handle.insert_key(
   File "/usr/local/lib/python3.10/site-packages/aries_askar/store.py\
 line 498, in insert_key
     await bindings.session_insert_key(
   File "/usr/local/lib/python3.10/site-packages/aries_askar/bindings.py\
 line 857, in session_insert_key
     await do_call_async(
 aries_askar.error.AskarError: Backend error
 Caused by: error returned from database: current transaction is aborted, commands ignored until end of transaction block
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/cloudagent/aries_cloudagent/protocols/didexchange/v1_0/routes.py\
 line 151, in didx_accept_invitation
     request = await didx_mgr.create_request(
   File "/cloudagent/aries_cloudagent/protocols/didexchange/v1_0/manager.py\
 line 270, in create_request
     my_info = await wallet.create_local_did(
   File "/cloudagent/aries_cloudagent/wallet/askar.py\
 line 207, in create_local_did
     raise WalletError("Error inserting key") from err
 aries_cloudagent.wallet.error.WalletError: Error inserting key
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/ddtrace/contrib/aiohttp/middlewares.py\
 line 61, in attach_context
     response = await handler(request)
   File "/cloudagent/aries_cloudagent/admin/server.py\
 line 159, in ready_middleware
     return await handler(request)
   File "/cloudagent/aries_cloudagent/admin/server.py\
 line 196, in debug_middleware
     return await handler(request)
   File "/usr/local/lib/python3.10/site-packages/aiohttp_apispec/middlewares.py\
 line 45, in validation_middleware
     return await handler(request)
   File "/cloudagent/aries_cloudagent/admin/server.py\
 line 339, in check_multitenant_authorization
     return await handler(request)
   File "/cloudagent/aries_cloudagent/admin/server.py\
 line 383, in setup_context
     return await task
   File "/cloudagent/aries_cloudagent/protocols/didexchange/v1_0/routes.py\
 line 161, in didx_accept_invitation
     raise web.HTTPBadRequest(reason=err.roll_up) from err
 aiohttp.web_exceptions.HTTPBadRequest: Error inserting key. Backend error. Caused by: error returned from database: current transaction is aborted, commands ignored until end of transaction block.
`

**Comment by andrewwhitehead** [comment]
Hm, it looks like this might be the bit that needs fixing (`txn_depth > 1`). I can test that out and maybe get rid of the `false_txn` flag.

```
impl<'a, DB: ExtDatabase> Drop for DbSessionActive<'a, DB> {
    fn drop(&mut self) {
        if self.txn_depth > 1 && !self.false_txn {
            info!("Roll-back dropped nested transaction");
            DB::TransactionManager::start_rollback(self.connection_mut());
        }
    }
}
```

**Comment by andrewwhitehead** [comment]
I added another PR: https://github.com/hyperledger/aries-askar/pull/45 if you'd like to test that.

**Comment by reflectivedevelopment** [comment]
I'll test that.

**Pull request closed without merging**
