### PR TITLE
Updates to the README and other Admin files in the repository

### PR DESCRIPTION
**Pull request by swcurran**
Signed-off-by: Stephen Curran <swcurran@gmail.com>

### CODE REVIEW

**Comment by swcurran** [comment]
@andrewwhitehead -- note the reference in the readme that link to the indy-wallet documents. Is it safe enough to reference those (with the caveat that I put in) or are we better to leave them off until we get an Askar-specific version of the documents?

What's up with this documentation only PR failing tests?  :-)

**Comment by andrewwhitehead** [comment]
I think it's fine to reference indy-wallet, although the implementation details are not all the same. It's based on the specifications (and reverse engineering) of the indy-wallet format, not the code.

**Comment by swcurran** [comment]
That’s what I was trying to say — sounds like I missed the mark a bit.  I’ll look to see if I can make that clearer.

**Comment by swcurran** [comment]
Updated that phrase.  Good enough?

**Review by andrewwhitehead — APPROVED** [review]

**Pull request merged**
