### PR TITLE
Add DbSessionTxn separate from DbSessionActive

### PR DESCRIPTION
**Pull request by andrewwhitehead**

### CODE REVIEW

**Comment by reflectivedevelopment** [comment]
It looks like we roll back all the time now. I'm seeing "src/backend/db_utils.rs:166 | Dropped transaction: roll-back" on all calls.

test-agent-1     | 2022-05-06 16:36:41,071 aries_askar.native.aries_askar.ffi.store INFO        src/ffi/store.rs:526 | Started session SessionHandle(2013) on store StoreHandle(2) (txn: false)
test-agent-1     | 2022-05-06 16:36:41,071 aries_askar.native.aries_askar.backend.db_utils INFO         src/backend/db_utils.rs:166 | Dropped transaction: roll-back
test-agent-1     | 2022-05-06 16:36:41,073 aries_askar.native.aries_askar.backend.db_utils INFO         src/backend/db_utils.rs:104 | Acquire pool connection
test-agent-1     | 2022-05-06 16:36:41,073 aries_askar.native.aries_askar.backend.db_utils INFO         src/backend/db_utils.rs:282 | Start transaction
test-agent-1     | 2022-05-06 16:36:41,075 aries_askar.native.aries_askar.backend.db_utils INFO         src/backend/db_utils.rs:315 | Commit transaction
test-agent-1     | 2022-05-06 16:36:41,079 aries_askar.native.aries_askar.ffi.store INFO        src/ffi/store.rs:1008 | Closed session SessionHandle(2013)
test-agent-1     | 2022-05-06 16:36:41,079 aries_askar.native.aries_askar.backend.db_utils INFO         src/backend/db_utils.rs:166 | Dropped transaction: roll-back

**Comment by andrewwhitehead** [comment]
Sorry, just added another quick fix.

**Comment by reflectivedevelopment** [comment]
No change

**Comment by andrewwhitehead** [comment]
Hm, it looks fine to me running the following test.

`python3 -m pytest --log-cli-level=debug -k test_txn_basic`

```
INFO     aries_askar.native.aries_askar.ffi.store:lib.py:161 	src/ffi/store.rs:526 | Started session SessionHandle(1) on store StoreHandle(1) (txn: true)
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:104 | Acquire pool connection
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:108 | Start transaction
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:148 | Commit transaction on close
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:170 | Dropped pool connection
INFO     aries_askar.native.aries_askar.ffi.store:lib.py:161 	src/ffi/store.rs:1008 | Closed session SessionHandle(1)
INFO     aries_askar.native.aries_askar.ffi.store:lib.py:161 	src/ffi/store.rs:526 | Started session SessionHandle(2) on store StoreHandle(1) (txn: false)
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:104 | Acquire pool connection
INFO     aries_askar.native.aries_askar.ffi.store:lib.py:161 	src/ffi/store.rs:1008 | Closed session SessionHandle(2)
INFO     aries_askar.native.aries_askar.backend.db_utils:lib.py:161 	src/backend/db_utils.rs:170 | Dropped pool connection
```

**Comment by reflectivedevelopment** [comment]
I'll give it another shot. I'm using it inside of Acapy

**Pull request merged**
